export const GAME_CONFIG = {
  periods: 8,
  periodsPerYear: 4,
  seed: 1947,
  starting: {
    customers: 260,
    avgSpend: 9600,
    grossMarginPct: 0.18,
    retentionPct: 0.89,
    serviceScore: 74,
    capacity: 320,
    cash: 450000,
    salesReps: 8,
    syscoPressure: 0.5,
  },
  segments: {
    Independent: { market: 1.0, spend: 1.0, retentionFitPremium: 0.01 },
    Chains: { market: 0.8, spend: 1.15, retentionFitPremium: -0.005 },
    Institutions: { market: 0.7, spend: 1.25, retentionFitPremium: 0.012 },
    Retail: { market: 0.65, spend: 1.1, retentionFitPremium: 0.0 },
  },
  coefficients: {
    baseAcquireRate: 0.08,
    marketingAcquireBoost: 0.12,
    repAcquireBoost: 0.014,
    serviceAcquireBoost: 0.0016,
    baseChurn: 0.12,
    serviceChurnReduction: 0.0015,
    aggressivePricingAcquireBoost: 0.03,
    premiumPricingAcquirePenalty: -0.025,
    premiumPricingGmBoost: 0.018,
    aggressivePricingGmPenalty: -0.02,
    cheapestSupplierGmBoost: 0.012,
    reliableSupplierGmPenalty: -0.008,
    premiumMixGmBoost: 0.014,
    valueMixGmPenalty: -0.01,
    spoilageBase: 0.02,
    spoilagePremiumAdd: 0.015,
    spoilageControlLow: 0.0,
    spoilageControlMed: -0.006,
    spoilageControlHigh: -0.012,
    serviceTargetCost: { Low: 0.015, Med: 0.019, High: 0.024 },
    serviceTargetBase: { Low: -4, Med: 0, High: 5 },
  },
  costs: {
    warehouseFixed: 150000,
    warehouseVarPct: 0.018,
    transportVarPct: 0.022,
    repCost: 23000,
    techAdminFixed: 90000,
    techAdminVarPct: 0.008,
    capacityCost: { None: 0, Small: 35000, Medium: 70000 },
    capacityGain: { None: 0, Small: 25, Medium: 55 },
  },
  events: [
    { name: 'Fuel prices blip up', chance: 0.14, effect: { transportPctDelta: 0.003 }, text: 'Delivery routes got pricier this period.' },
    { name: 'Labor tightness', chance: 0.12, effect: { warehousePctDelta: 0.003 }, text: 'Warehouse labor costs ticked upward.' },
    { name: 'Local “eat fresh” trend', chance: 0.1, effect: { premiumDemandBoost: 0.02 }, text: 'Fresh and better-for-you demand accelerated.' },
    { name: 'Sysco promo blitz', chance: 0.14, effect: { acquirePenalty: 0.018 }, text: 'Aggressive promos made acquisition tougher.' },
    { name: 'Supplier hiccup', chance: 0.1, effect: { serviceDelta: -5 }, text: 'Supply reliability dipped this quarter.' },
  ],
  valuation: {
    baseMultiple: 6.0,
    growthWeight: 1.2,
    gmWeight: 1.0,
    retentionWeight: 1.0,
    serviceWeight: 0.8,
    maxAdjustment: 1.0,
  },
};
